### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by kf6kjg** [InWorldz/aperture#2]
Could this be easily ported to Linux? I've not yet explored the codebase other than to ascertain whether it was multi-OS already: it appears to be Windows only at the moment.

Alternatively, could an already established Linux-based server fill the shoes or is there use-case specific code involved?  If so, what's the high-level description of said code?

**Comment by ddaeschler** [comment]
The code should already be mostly cross platform ready. It just may need some cake tweaks.

**Comment by ddaeschler** [comment]
Cmake not cake. Dammit autocorrect

**Comment by kf6kjg** [comment]
lol.  From looking around the codebase further I find that it may be that
the majority of the code is ready, but simply that there's (no `main()` for
the other platforms)[
https://github.com/InWorldz/aperture/search?utf8=%E2%9C%93&q=main%28]: the
only place, other than tests, that I find one is in `win_main.cpp` - which
has `#if defined(_WIN32)` inclusion guards surrounding it.

As Aperture and OpenJPEG are the next things slowing down getting my Linux
region online I think I'll attempt this when I can: I'm open to any
pointers, gotchas, and advice.

**Comment by kf6kjg** [comment]
Fixed some time ago :/
